/* Copyright © Alex Malmyguine, 2022
 * All right reserved
 * This program remains the property of the copyright owner at all times.
 * It cannot be used for any purposes without express, written permission from the copyright owner.
 * Intellectual property contained in this program is protected by Canadian, US, and international copyright laws.
 * 
 * Generated by: Scripts/HtmlTranslation.php
 */
namespace MAGNASite.Lib
{
    [Flags]
    internal enum HtmlDocumentTypes
    {
        ENT_COMPAT,     // Table will contain entities for double-quotes, but not for single-quotes.
        ENT_QUOTES,     // Table will contain entities for both double and single quotes.
        ENT_NOQUOTES,   // Table will neither contain entities for single quotes nor for double quotes.
        ENT_SUBSTITUTE, // Replace invalid code unit sequences with a Unicode Replacement Character U+FFFD (UTF-8) or &#xFFFD; (otherwise) instead of returning an empty string.
        ENT_HTML401,    // Table for HTML 4.01.
        ENT_XML1,       // Table for XML 1.
        ENT_XHTML,      // Table for XHTML.
        ENT_HTML5,      // Table for HTML 5.
    }
}
