/* Copyright © Alex Malmyguine, 2022
 * All right reserved
 * This program remains the property of the copyright owner at all times.
 * It cannot be used for any purposes without express, written permission from the copyright owner.
 * Intellectual property contained in this program is protected by Canadian, US, and international copyright laws.
 * 
 * Generated by: Scripts/HtmlTranslation.php
 */
namespace MAGNASite.Lib
{
	internal static class HTML_ENTITIES
	{
<?php
//echo "ABDAY_(1-7)		=".ABDAY_(1-7)		;
//echo "DAY_(1-7)			=".DAY_(1-7)		;	
//echo "ABMON_(1-12)		=".ABMON_(1-12)		;
//echo "MON_(1-12)		=".MON_(1-12)		;
echo "AM_STR			=".AM_STR			;
echo "PM_STR			=".PM_STR			;
echo "D_T_FMT			=".D_T_FMT			;
echo "D_FMT				=".D_FMT			;	
echo "T_FMT				=".T_FMT			;	
echo "T_FMT_AMPM		=".T_FMT_AMPM		;
echo "ERA				=".ERA				;
echo "ERA_YEAR			=".ERA_YEAR			;
echo "ERA_D_T_FMT		=".ERA_D_T_FMT		;
echo "ERA_D_FMT			=".ERA_D_FMT		;	
echo "ERA_T_FMT			=".ERA_T_FMT		;	
echo "INT_CURR_SYMBOL	=".INT_CURR_SYMBOL	;
echo "CURRENCY_SYMBOL	=".CURRENCY_SYMBOL	;
echo "CRNCYSTR			=".CRNCYSTR			;
echo "MON_DECIMAL_POINT	=".MON_DECIMAL_POINT;	
echo "MON_THOUSANDS_SEP	=".MON_THOUSANDS_SEP;	
echo "MON_GROUPING		=".MON_GROUPING		;
echo "POSITIVE_SIGN		=".POSITIVE_SIGN	;	
echo "NEGATIVE_SIGN		=".NEGATIVE_SIGN	;	
echo "INT_FRAC_DIGITS	=".INT_FRAC_DIGITS	;
echo "FRAC_DIGITS		=".FRAC_DIGITS		;
echo "P_CS_PRECEDES 	=".P_CS_PRECEDES 	;
echo "P_SEP_BY_SPACE	=".P_SEP_BY_SPACE	;
echo "N_CS_PRECEDES 	=".N_CS_PRECEDES 	;
echo "N_SEP_BY_SPACE	=".N_SEP_BY_SPACE	;
echo "P_SIGN_POSN 		=".P_SIGN_POSN 		;
echo "N_SIGN_POSN		=".N_SIGN_POSN		;
echo "DECIMAL_POINT		=".DECIMAL_POINT	;	
echo "RADIXCHAR			=".RADIXCHAR		;	
echo "THOUSANDS_SEP		=".THOUSANDS_SEP	;	
echo "THOUSEP			=".THOUSEP			;
echo "GROUPING 	 		=".GROUPING 	 	;	
echo "YESEXPR			=".YESEXPR			;
echo "NOEXPR			=".NOEXPR			;
echo "YESSTR			=".YESSTR			;
echo "NOSTR				=".NOSTR			;
echo "CODESET			=".CODESET			;
?>
	}
}
