<pre>
/* Copyright © Alex Malmyguine, 2022
 * All right reserved
 * This program remains the property of the copyright owner at all times.
 * It cannot be used for any purposes without express, written permission from the copyright owner.
 * Intellectual property contained in this program is protected by Canadian, US, and international copyright laws.
 * 
 * Generated by: Scripts/HtmlTranslation.php
 */
<?php
    echo "public const int PHP_URL_SCHEME       = " . PHP_URL_SCHEME       ."; //                                                                                                                                                    \n";
    echo "public const int PHP_URL_HOST         = " . PHP_URL_HOST         ."; // Outputs the hostname of the URL parsed.                                                                                                            \n";
    echo "public const int PHP_URL_PORT         = " . PHP_URL_PORT         ."; // Outputs the port of the URL parsed.                                                                                                                \n";
    echo "public const int PHP_URL_USER         = " . PHP_URL_USER         ."; // Outputs the user of the URL parsed.                                                                                                                \n";
    echo "public const int PHP_URL_PASS         = " . PHP_URL_PASS         ."; // Outputs the password of the URL parsed.                                                                                                            \n";
    echo "public const int PHP_URL_PATH         = " . PHP_URL_PATH         ."; // Outputs the path of the URL parsed.                                                                                                                \n";
    echo "public const int PHP_URL_QUERY        = " . PHP_URL_QUERY        ."; // Outputs the query string of the URL parsed.                                                                                                        \n";
    echo "public const int PHP_URL_FRAGMENT     = " . PHP_URL_FRAGMENT     ."; // Outputs the fragment (string after the hashmark #) of the URL parsed. //The following constants are meant to be used with http_build_query().      \n";
    echo "public const int PHP_QUERY_RFC1738    = " . PHP_QUERY_RFC1738    ."; // Encoding is performed per » RFC 1738 and the application/x-www-form-urlencoded media type, which implies that spaces are encoded as plus (+) signs.\n";
    echo "public const int PHP_QUERY_RFC3986    = " . PHP_QUERY_RFC3986    ."; // Encoding is performed according to » RFC 3986, and spaces will be percent encoded (%20).                                                           \n";
?>
</pre>
